--SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SEQUENCE office_process_history_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE office_process_history (
    id              BIGINT GENERATED BY DEFAULT AS SEQUENCE office_process_history_seq PRIMARY KEY,
    survey_type_id  INTEGER,
    status          VARCHAR(20 CHAR) NOT NULL,
    fire_date       DATE NOT NULL,
    duration        INTEGER,
    user_type       VARCHAR(20 CHAR),
    user_diagnostic VARCHAR(20 CHAR),
    user_age_group  INTEGER,
);

COMMENT ON TABLE office_process_history IS 'История работы кабинетов';

COMMENT ON COLUMN office_process_history.id IS 'Id';
-- todo
