--SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS SEQUENCE users_seq PRIMARY KEY,
    first_name  VARCHAR(20 CHAR),
    last_name   VARCHAR(20 CHAR),
    type        VARCHAR(20 CHAR),
    status      VARCHAR(20 CHAR),
    updated_at   DATE,
    diagnostic      VARCHAR(20 CHAR),
    birth_date   DATE
);

COMMENT ON TABLE users IS 'Пациенты';

COMMENT ON COLUMN users.id IS 'Id';
COMMENT ON COLUMN users.first_name IS 'Имя';
COMMENT ON COLUMN users.last_name IS 'Фамилия';
COMMENT ON COLUMN users.type IS 'Тип';
-- todo
