SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SEQUENCE user_process_history_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE user_process_history (
    id              BIGINT GENERATED BY DEFAULT AS SEQUENCE user_process_history_seq PRIMARY KEY,
    user_id         INTEGER,
    office_id       INTEGER,
    status          VARCHAR2(20 CHAR) NOT NULL,
    fire_date       DATE NOT NULL,
    duration        INTEGER
);

COMMENT ON TABLE user_process_history IS 'История работы с пациентами';

COMMENT ON COLUMN user_process_history.id IS 'Id';
-- todo
