SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SEQUENCE queue_items_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE queue_items (
    id           BIGINT GENERATED BY DEFAULT AS SEQUENCE queue_items_seq PRIMARY KEY,
    user_id      INTEGER NOT NULL,
    office_id    INTEGER,
    est_duration INTEGER,
    onum         INTEGER
);

COMMENT ON TABLE queue_items IS 'Элементы в очередях в кабинеты';

COMMENT ON COLUMN queue_items.id IS 'Id';
-- todo
