SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SEQUENCE survey_types_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE survey_types (
    id          BIGINT GENERATED BY DEFAULT AS SEQUENCE survey_types_seq PRIMARY KEY,
    name        VARCHAR2(50 CHAR)
);

COMMENT ON TABLE survey_types IS 'Кабинеты';

COMMENT ON COLUMN survey_types.id IS 'Id';
COMMENT ON COLUMN survey_types.name IS 'Название';
-- todo
