SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SEQUENCE offices_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE offices (
    id             BIGINT GENERATED BY DEFAULT AS SEQUENCE offices_seq PRIMARY KEY,
    name           VARCHAR2(50 CHAR),
    survey_type_id INTEGER,
    status         VARCHAR2(20 CHAR),
    updated_at     DATE
);

COMMENT ON TABLE offices IS 'Кабинеты';

COMMENT ON COLUMN offices.id IS 'Id';
COMMENT ON COLUMN offices.name IS 'Название';
-- todo
