SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SEQUENCE route_sheet_items_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE route_sheet_items (
    id               BIGINT GENERATED BY DEFAULT AS SEQUENCE route_sheet_items_seq PRIMARY KEY,
    user_id          INTEGER NOT NULL,
    survey_type_id   INTEGER,
    priority         DOUBLE,
    visited          INTEGER,
    onum             INTEGER,
);

COMMENT ON TABLE route_sheet_items IS 'Элементы в маршрутных листах';

COMMENT ON COLUMN route_sheet_items.id IS 'Id';
-- todo
