delete from Practitioner;

--todo это временно, пока не дали данные
select resource_create('{"resourceType": "Practitioner", "id": "фельдшер_Колосова", "name": [{"use": "official", "text": "Колосова Александра Александровна", "given": ["Александра"], "suffix": ["Александровна"], "family": "Колосова"}], "gender": "female", "qualification": {"code": {"coding": [{"code": "Paramedic", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "мед_работник_диагностики_Сидорова", "name": [{"use": "official", "text": "Сидорова Александра Александровна", "given": ["Александра"], "suffix": ["Александровна"], "family": "Заборова"}], "gender": "female", "qualification": {"code": {"coding": [{"code": "Diagnostic_assistant", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "мед_работник_диагностики_Иванова", "name": [{"use": "official", "text": "Сидорова Александра Александровна", "given": ["Александра"], "suffix": ["Александровна"], "family": "Заборова"}], "gender": "female", "qualification": {"code": {"coding": [{"code": "Diagnostic_assistant", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "терапевт_Петров", "name": [{"use": "official", "text": "Петров Петр Валерьевич", "given": ["Петр"], "suffix": ["Валерьевич"], "family": "Петров"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Therapist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "терапевт_Иванов", "name": [{"use": "official", "text": "Иванов Петр Валерьевич", "given": ["Петр"], "suffix": ["Валерьевич"], "family": "Иванов"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Therapist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "хирург_Петров", "name": [{"use": "official", "text": "Петров Петр Валерьевич", "given": ["Петр"], "suffix": ["Валерьевич"], "family": "Петров"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Surgeon", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "хирург_Иванов", "name": [{"use": "official", "text": "Иванов Петр Валерьевич", "given": ["Иван"], "suffix": ["Валерьевич"], "family": "Иванов"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Surgeon", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "невролог_Петров", "name": [{"use": "official", "text": "Петров Петр Валерьевич", "given": ["Иван"], "suffix": ["Валерьевич"], "family": "Петров"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Neurologist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "невролог_Иванов", "name": [{"use": "official", "text": "Иванов Петр Валерьевич", "given": ["Иван"], "suffix": ["Валерьевич"], "family": "Иванов"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Neurologist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "уролог_Петров", "name": [{"use": "official", "text": "Петров Петр Валерьевич", "given": ["Петров"], "suffix": ["Валерьевич"], "family": "Петров"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Urologist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "уролог_Иванов", "name": [{"use": "official", "text": "Иванов Петр Валерьевич", "given": ["Иванов"], "suffix": ["Валерьевич"], "family": "Иванов"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Urologist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "гинеколог_Петров", "name": [{"use": "official", "text": "Петров Петр Валерьевич", "given": ["Иван"], "suffix": ["Валерьевич"], "family": "Петров"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Gynecologist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
select resource_create('{"resourceType": "Practitioner", "id": "гинеколог_Иванов", "name": [{"use": "official", "text": "Иванов Петр Валерьевич", "given": ["Иван"], "suffix": ["Валерьевич"], "family": "Иванов"}], "gender": "male", "qualification": {"code": {"coding": [{"code": "Gynecologist", "system": "ValueSet/Practitioner_qualifications"}]}}, "extension": {"blocked": false}}'::jsonb);
