delete from valueset r where r.resource ->> 'url' = 'ValueSet/Observation_types';
delete from concept r where r.resource ->> 'system' = 'ValueSet/Observation_types';

select resource_create('{"resourceType": "ValueSet", "id": "Observation_types", "url": "ValueSet/Observation_types", "description": "Типы процедур/услуг", "name": "Observation_types", "title": "Типы процедур/услуг", "status": "active"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Vital_signs", "code": "Vital_signs", "parentCode": null, "display": "Жизненно важные физиологические показатели", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Blood_pressure_upper_level", "code": "Blood_pressure_upper_level", "parentCode": "Vital_signs", "display": "Артериальное давление верхняя граница", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Blood_pressure_lower_level", "code": "Blood_pressure_lower_level", "parentCode": "Vital_signs", "display": "Артериальное давление нижняя граница", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Heart_rate", "code": "Heart_rate", "display": "Частота сердечных сокращений", "parentCode": "Vital_signs", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Pulse_rate", "code": "Pulse_rate", "display": "Частота пульса", "parentCode": "Vital_signs", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Breathing_rate", "code": "Breathing_rate", "display": "Частота дыхания", "parentCode": "Vital_signs", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Body_temperature", "code": "Body_temperature", "display": "Температура тела", "parentCode": "Vital_signs", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Electrocardiogram", "code": "Electrocardiogram", "display": "Электрокардиограмма", "parentCode": "Vital_signs", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Blood_oxygen_saturation", "code": "Blood_oxygen_saturation", "parentCode": "Vital_signs", "display": "Степень насыщения крови кислородом", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Weight", "code": "Weight", "parentCode": "Vital_signs", "display": "Вес", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Height", "code": "Height", "parentCode": "Vital_signs", "display": "Рост", "system": "ValueSet/Observation_types"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Observation_types:Pain_intensity", "code": "Pain_intensity", "parentCode": "Vital_signs", "display": "Интенсивность боли", "system": "ValueSet/Observation_types"}'::jsonb);


select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Inspection", "display": "Осмотры", "id": "Observation_types:Inspection", "priority": "0.1"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Ultrasound", "display": "УЗИ", "id": "Observation_types:Ultrasound"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Blood_analysis", "display": "Исследования крови", "id": "Observation_types:Blood_analysis", "priority": "0.8"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Urine_analysis", "display": "Исследование мочи", "id": "Observation_types:Urine_analysis", "priority": "0.9"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "ECG", "display": "ЭКГ", "id": "Observation_types:ECG"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "X-ray", "display": "Рентген", "id": "Observation_types:X-ray"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Computer_tomography", "display": "Компьютерная томография", "id": "Observation_types:Computer_tomography"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Gastroscopy", "display": "Гастроскопия", "id": "Observation_types:Gastroscopy", "priority": "0.2"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Bronchoscopy", "display": "Бронхоскопия", "id": "Observation_types:Bronchoscopy"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Colonoscopy", "display": "Колоноскопия", "id": "Observation_types:Colonoscopy"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": null, "code": "Bandage", "display": "Перевязка", "id": "Observation_types:Bandage"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "B01.044.001", "display": "Регистрация экстренного пациента", "id": "Observation_types:B01.044.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "Clinical_impression", "display": "Обращение в скорую помощь", "id": "Observation_types:Clinical_impression"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "Inspection_on_reception", "display": "Первичный осмотр при регистрации обращения", "id": "Observation_types:Inspection_on_reception"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтФтизиатр", "display": "Осмотр (консультация) врача фтизиатра в стационаре", "id": "Observation_types:СтФтизиатр.Inspection_of_a_TB_doctor"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтГинек", "display": "Осмотр (консультация) врача-акушера-гинеколога в стационаре", "id": "Observation_types:СтГинек.Inspection_of_a_gynaecologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтДермат", "display": "Осмотр (консультация) врача-дерматовенеролога в стационаре", "id": "Observation_types:СтДермат.Inspection_of_a_dermatovenerologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтИнф", "display": "Осмотр (консультация) врача-инфекциониста в стационаре", "id": "Observation_types:СтИнф.Inspection_of_an_infectious_disease_specialist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтКардиол", "display": "Осмотр (консультация) врача-кардиолога в стационаре", "id": "Observation_types:СтКардиол.Inspection_of_a_cardiologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "ST_KLIN_FARM", "display": "Осмотр (консультация) врача-клинического фармаколога в стационаре", "id": "Observation_types:ST_KLIN_FARM.Inspection_of_a_doctor-clinical_pharmacologist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтНев", "display": "Осмотр (консультация) врача-невролога в стационаре", "id": "Observation_types:СтНев.Inspection_of_a_neurologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтОнк", "display": "Осмотр (консультация) врача-онколога в стационаре", "id": "Observation_types:СтОнк.Inspection_of_an_oncologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СТлор", "display": "Осмотр (консультация) врача-отоларинголога в стационаре", "id": "Observation_types:СТлор.Inspection_of_an_otolaryngologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтОфт", "display": "Осмотр (консультация) врача-офтальмолога в стационаре", "id": "Observation_types:СтОфт.Inspection_of_an_ophthalmologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтПс", "display": "Осмотр (консультация) врача-психиатра в стационаре", "id": "Observation_types:СтПс.Inspection_of_a_psychiatrist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтРевмат", "display": "Осмотр (консультация) врача-ревматолога в стационаре", "id": "Observation_types:СтРевмат.Inspection_of_a_rheumatologist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтТер", "display": "Осмотр (консультация) врача-терапевта в стационаре", "id": "Observation_types:СтТер.Inspection_of_a_therapeutist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтУрол", "display": "Осмотр (консультация) врача-уролога в стационаре", "id": "Observation_types:СтУрол.Inspection_of_a_urologist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтХир", "display": "Осмотр (консультация) врача-хирурга в стационаре", "id": "Observation_types:СтХир.Inspection_of_a_surgeon"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "СтЭндокр", "display": "Осмотр (консультация) врача-эндокринолога в стационаре", "id": "Observation_types:СтЭндокр.Inspection_of_the_endocrinologist"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "B01.020.001", "display": "Прием (осмотр, консультация) врача по лечебной физкультуре", "id": "Observation_types:B01.020.001.Reception_(examination,_consultation)_of_a_physician_in_physiotherapy_exercises"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Inspection", "code": "B01.054.01", "display": "Прием (осмотр, консультация) врача-физиотерапевта первичный", "id": "Observation_types:B01.054.01.Primary_reception_(examination,_consultation)_of_a_physiotherapist"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "ECG", "code": "А05.10.006", "display": "Регистрация электрокардиограммы", "id": "Observation_types:А05.10.006"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "ECG", "code": "A05.10.004", "display": "Расшифровка, описание и интерпретация электрокардиографических данных", "id": "Observation_types:A05.10.004"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.28.002.004", "display": "Ультразвуковое исследование уретры", "id": "Observation_types:A04.28.002.004"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.16.001", "display": "Ультразвуковое исследование органов брюшной полости (комплексное)", "id": "Observation_types:A04.16.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.28.002.001", "display": "Ультразвуковое исследование почек", "id": "Observation_types:A04.28.002.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.21.001", "display": "Ультразвуковое исследование предстательной железы", "id": "Observation_types:A04.21.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.20.001", "display": "Ультразвуковое исследование матки и придатков трансабдоминальное", "id": "Observation_types:A04.20.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.20.001.001", "display": "Ультразвуковое исследование матки и придатков трансвагинальное", "id": "Observation_types:A04.20.001.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.30.006", "display": "Ультразвуковое исследование брюшины", "id": "Observation_types:A04.30.006"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.04.001", "display": "Ультразвуковое исследование сустава", "id": "Observation_types:A04.04.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.28.003", "display": "Ультразвуковое исследование органов мошонки", "id": "Observation_types:A04.28.003"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.28.002.003", "display": "Ультразвуковое исследование мочевого пузыря", "id": "Observation_types:A04.28.002.003"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.20.002", "display": "Ультразвуковое исследование молочных желез", "id": "Observation_types:A04.20.002"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.12.001.001", "display": "Ультразвуковая допплерография артерий нижних конечностей", "id": "Observation_types:A04.12.001.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.12.003", "display": "Дуплексное сканирование аорты", "id": "Observation_types:A04.12.003"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.12.001", "display": "Ультразвуковая допплерография артерий верхних конечностей", "id": "Observation_types:A04.12.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.12.002.002", "display": "Ультразвуковая допплерография вен нижних конечностей", "id": "Observation_types:A04.12.002.002"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.12.002.003", "display": "Ультразвуковая допплерография вен верхних конечностей", "id": "Observation_types:A04.12.002.003"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.06.002", "display": "Ультразвуковое исследование лимфатических узлов (одна анатомическая зона)", "id": "Observation_types:A04.06.002"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.01.001", "display": "Ультразвуковое исследование мягких тканей (одна анатомическая зона)", "id": "Observation_types:A04.01.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Ultrasound", "code": "A04.09.001", "display": "Ультразвуковое исследование плевральной полости", "id": "Observation_types:A04.09.001"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.04.004", "display": "Рентгенография лучезапястного сустава", "id": "Observation_types:A06.04.004"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.022", "display": "Рентгенография ключицы", "id": "Observation_types:A06.03.022"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.28.013", "display": "Обзорная урография (рентгенография мочевыделительной системы", "id": "Observation_types:А06.28.013"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.28.001", "display": "Рентгенография почек и мочевыводящих путей", "id": "Observation_types:А06.28.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.28.002", "display": "Внутривенная урография", "id": "Observation_types:А06.28.002"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.28.004", "display": "Ретроградная уретеропиелография", "id": "Observation_types:А06.28.004"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.28.005", "display": "Негативная и двойная контрастная цистография или уретероцистография", "id": "Observation_types:А06.28.005"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.09.007", "display": "Рентгенография легких", "id": "Observation_types:А06.09.007"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.010", "display": "Рентгенография шейного отдела позвоночника", "id": "Observation_types:А06.03.010"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.16.008", "display": "Рентгенография желудка и двенадцатиперстной кишки, двойной контраст", "id": "Observation_types:A06.16.008"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.015", "display": "Рентгенография поясничного отдела позвоночника", "id": "Observation_types:А06.03.015"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.013", "display": "Рентгенография грудного отдела позвоночника", "id": "Observation_types:А06.03.013"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.005", "display": "Рентгенография всего черепа, в одной или более проекциях", "id": "Observation_types:A06.03.005"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.04.003", "display": "Рентгенография локтевого сустава", "id": "Observation_types:А06.04.003"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.04.010", "display": "Рентгенография плечевого сустава", "id": "Observation_types:А06.04.010"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.04.011", "display": "Рентгенография тазобедренного сустава", "id": "Observation_types:А06.04.011"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.04.005", "display": "Рентгенография коленного сустава", "id": "Observation_types:А06.04.005"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.04.012", "display": "Рентгенография голеностопного сустава", "id": "Observation_types:А06.04.012"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.16.001.002", "display": "Рентгеноскопия пищевода с контрастированием", "id": "Observation_types:A06.16.001.002"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.16.007", "display": "Рентгеноскопия желудка и двенадцатиперстной кишки", "id": "Observation_types:A06.16.007"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.18.001", "display": "Ирригоскопия", "id": "Observation_types:A06.18.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.08.003", "display": "Рентгенография придаточных пазух носа", "id": "Observation_types:A06.08.003"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.26.001", "display": "Рентгенография глазницы", "id": "Observation_types:A06.26.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.023", "display": "Рентгенография ребра(ер)", "id": "Observation_types:A06.03.023"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.017", "display": "Рентгенография крестца и копчика", "id": "Observation_types:A06.03.017"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.033", "display": "Рентгенография фаланг пальцев кисти", "id": "Observation_types:A06.03.033"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.041", "display": "Рентгенография всего таза", "id": "Observation_types:A06.03.041"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.032", "display": "Рентгенография кисти руки", "id": "Observation_types:A06.03.032"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.050", "display": "Рентгенография пяточной кости", "id": "Observation_types:A06.03.050"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.03.049", "display": "Рентгенография предплюсны", "id": "Observation_types:A06.03.049"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.051", "display": "Рентгенография плюсны и фаланг пальцев стопы", "id": "Observation_types:А06.03.051"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.048", "display": "Рентгенография лодыжки", "id": "Observation_types:А06.03.048"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.053", "display": "Рентгенография стопы в двух проекциях", "id": "Observation_types:А06.03.053"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.30.004", "display": "Обзорный снимок брюшной полости и органов малого таза", "id": "Observation_types:А06.30.004"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.30.004.001", "display": "Обзорная рентгенография органов брюшной полости", "id": "Observation_types:A06.30.004.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.042", "display": "Рентгенография головки и шейки бедренной кости", "id": "Observation_types:А06.03.042"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "А06.03.043", "display": "Рентгенография бедренной кости", "id": "Observation_types:А06.03.043"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "X-ray", "code": "A06.30.008", "display": "Фистулография", "id": "Observation_types:A06.30.008"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Computer_tomography", "code": "А06.23.004", "display": "Компьютерная томография головного мозга", "id": "Observation_types:А06.23.004"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Gastroscopy", "code": "A03.16.001", "display": "Эзофагогастродуоденоскопия", "id": "Observation_types:A03.16.001"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Urine_analysis", "code": "B03.016.006", "display": "Общий анализ мочи", "id": "Observation_types:B03.016.006"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Urine_analysis", "code": "A09.28.029", "display": "Исследование мочи на хорионический гонадотропин", "id": "Observation_types:A09.28.029"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "B03.016.002", "display": "Общий (клинический) анализ крови ", "id": "Observation_types:B03.016.002"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.100.001", "display": "Исследование биологического материала (крови, мочи) на содержание алкоголя", "id": "Observation_types:A09.05.100.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.010", "display": "Исследование уровня общего белка в крови", "id": "Observation_types:A09.05.010"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.017", "display": "Исследование уровня мочевины в крови", "id": "Observation_types:A09.05.017"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.020", "display": "Исследование уровня креатинина в крови", "id": "Observation_types:A09.05.020"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.022", "display": "Исследование уровня свободного и связанного билирубина в крови", "id": "Observation_types:A09.05.022"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.023", "display": "Исследование уровня глюкозы в крови", "id": "Observation_types:A09.05.023"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.041", "display": "Исследование уровня аспартат-трансаминазы в крови", "id": "Observation_types:A09.05.041"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.042", "display": "Исследование уровня аланин-трансаминазы в крови", "id": "Observation_types:A09.05.042"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.045", "display": "Исследование уровня амилазы в крови", "id": "Observation_types:A09.05.045"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.043.020", "display": "Исследование уровня креатинфосфокиназы-МВ в крови (КФК-МВ)", "id": "Observation_types:A09.05.043.020"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.193", "display": "Определение уровня тропонина в крови ( качественный)", "id": "Observation_types:A09.05.193"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.253.001", "display": "Исследование уровня тропонина I в крови (количественно)", "id": "Observation_types:A09.05.253.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.209", "display": "Исследование уровня прокальцитонина в крови", "id": "Observation_types:A09.05.209"}'::jsonb);
-- todo не может быть 2 одинаковых кода, тем не менее это один код, но нужно их различать: качественно или количественно. как это описать или задать уточняется
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.209", "display": "Исследование уровня прокальцитонина в крови (качественно)", "id": "Observation_types:A09.05.209"}'::jsonb);
-- select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.209", "display": "Исследование уровня прокальцитонина в крови (количественно)", "id": "Observation_types:A09.05.209"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.256", "display": "Исследование уровня N-терминального фрагмента прогормона мозгового натрийуретического пептида (NT-proBNP) в крови", "id": "Observation_types:A09.05.256"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.009", "display": "Определение концентрации C-реактивного белка в сыворотке крови", "id": "Observation_types:A09.05.009"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "А09.05.030", "display": "Исследование уровня натрия в крови", "id": "Observation_types:А09.05.030"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "А09.05.031", "display": "Исследование уровня калия в крови", "id": "Observation_types:А09.05.031"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "А09.05.034", "display": "Исследование уровня хлоридов в крови", "id": "Observation_types:А09.05.034"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.05.050", "display": "Исследование уровня фибриногена в крови", "id": "Observation_types:A09.05.050"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A09.20.003", "display": "Определение уровня Д-димера", "id": "Observation_types:A09.20.003"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A12.05.039.001", "display": "Определение активированного частичного тромбопластинового времени (АЧТВ) в плазме крови", "id": "Observation_types:A12.05.039.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "B03.05.006.002", "display": "Определение протромбинового времени, протромбинового индекса, МНО ", "id": "Observation_types:B03.05.006.002"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A12.05.005", "display": "Определение основных групп по системе AB0", "id": "Observation_types:A12.05.005"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A12.05.006", "display": "Определение антигена D системы Резус (резус-фактор)", "id": "Observation_types:A12.05.006"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Blood_analysis", "code": "A11.12.009", "display": "Взятие крови из периферической вены", "id": "Observation_types:A11.12.009"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Bronchoscopy", "code": "A03.09.001", "display": "Бронхоскопия", "id": "Observation_types:A03.09.001"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Colonoscopy", "code": "A03.18.001", "display": "Колоноскопия", "id": "Observation_types:A03.18.001"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Colonoscopy", "code": "A03.19.002", "display": "Ректороманоскопия", "id": "Observation_types:A03.19.002"}'::jsonb);

select resource_create('{"resourceType": "Concept", "system": "ValueSet/Observation_types", "parentCode": "Bandage", "code": "Перевязка", "display": "Перевязка", "id": "Observation_types:Перевязка"}'::jsonb);

