delete from valueset r where r.resource ->> 'url' = 'ValueSet/Practitioner_qualifications';
delete from concept r where r.resource ->> 'system' = 'ValueSet/Practitioner_qualifications';

select resource_create('{"resourceType": "ValueSet", "id": "Practitioner_qualifications", "description": "Специальности мед. работников", "name": "Practitioner_qualifications", "title": "Специальности мед. работников", "status": "active", "url": "ValueSet/Practitioner_qualifications"}'::jsonb);

--категории
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Therapist_category", "code": "Therapist_category", "system": "ValueSet/Practitioner_qualifications", "display": "Врач-терапевт", "priority": "1"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Gynecologist_category", "code": "Gynecologist_category", "system": "ValueSet/Practitioner_qualifications", "display": "Врач-гинеколог", "relativeGender": "female", "priority": "0.9"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Surgeon_category", "code": "Surgeon_category", "system": "ValueSet/Practitioner_qualifications", "display": "Врач-хирург", "priority": "0.8"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Neurologist_category", "code": "Neurologist_category", "system": "ValueSet/Practitioner_qualifications", "display": "Врач-невролог", "priority": "0.7"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Urologist_category", "code": "Urologist_category", "system": "ValueSet/Practitioner_qualifications", "display": "Врач-уролог", "priority": "0.6"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:KDL_category", "code": "KDL_category", "system": "ValueSet/Practitioner_qualifications", "display": "Мед. работник КДЛ", "priority": "0.5"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Paramedic_category", "code": "Paramedic_category", "system": "ValueSet/Practitioner_qualifications", "display": "Фельдшер", "priority": "0.4"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Diagnostic_assistant_category", "code": "Diagnostic_assistant_category", "system": "ValueSet/Practitioner_qualifications", "display": "Мед. работник диагностических исследований", "priority": "0.3"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Focused_specialist_category", "code": "Focused_specialist_category", "system": "ValueSet/Practitioner_qualifications", "display": "Мед. работник других специальностей", "priority": "0.2"}'::jsonb);
select resource_create('{"resourceType": "Concept", "id": "Practitioner_qualifications:Nursing_staff_category", "code": "Nursing_staff_category", "system": "ValueSet/Practitioner_qualifications", "display": "Средний медицинский персонал", "priority": "0.1"}'::jsonb);

--специальности
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Diagnostic_assistant_category", "code": "Radiologist", "display": "Врач-рентгенолог", "id": "Practitioner_qualifications:Radiologist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Diagnostic_assistant_category", "code": "X-ray_lab_assistant", "display": "Рентгенлаборант", "id": "Practitioner_qualifications:X-ray_lab_assistant"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Diagnostic_assistant_category", "code": "Ultrasound_doctor", "display": "Врач УЗД", "id": "Practitioner_qualifications:Ultrasound_doctor"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Urologist_category", "code": "Urologist", "display": "Врач-уролог", "id": "Practitioner_qualifications:Urologist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Surgeon_category", "code": "Surgeon", "display": "Врач-хирург", "id": "Practitioner_qualifications:Surgeon"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Gynecologist_category", "code": "Gynecologist_obstetrician", "display": "Врач акушер-гинеколог", "id": "Practitioner_qualifications:Gynecologist_obstetrician"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Therapist_category", "code": "Therapist", "display": "Врач-терапевт", "id": "Practitioner_qualifications:Therapist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Neurologist_category", "code": "Neurologist", "display": "Врач-невролог", "id": "Practitioner_qualifications:Neurologist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Focused_specialist_category", "code": "Anaesthesiologist-resuscitator", "display": "Врач-анестезиолог-реаниматолог", "id": "Practitioner_qualifications:Anaesthesiologist-resuscitator"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Paramedic_category", "code": "Paramedic", "display": "Фельдшер", "id": "Practitioner_qualifications:Paramedic"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Nursing_staff_category", "code": "Ms_procedural", "display": "М/с процедурная", "id": "Practitioner_qualifications:Ms_procedural"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Nursing_staff_category", "code": "Ms", "display": "М/с", "id": "Practitioner_qualifications:Ms"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Nursing_staff_category", "code": "Mb_procedural", "display": "М/б процедурной", "id": "Practitioner_qualifications:Mb_procedural"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Nursing_staff_category", "code": "Mb", "display": "М/б", "id": "Practitioner_qualifications:Mb"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Diagnostic_assistant_category", "code": "Endoscopist", "display": "Врач-эндоскопист", "id": "Practitioner_qualifications:Endoscopist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "Focused_specialist_category", "code": "Infectious_disease_physician", "display": "Врач-инфекционист", "id": "Practitioner_qualifications:Infectious_disease_physician"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "KDL_category", "code": "Medical_Laboratory_Technician", "display": "Медицинский лабораторный техник", "id": "Practitioner_qualifications:Medical_Laboratory_Technician"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "KDL_category", "code": "KDL_doctor", "display": "Врач КДЛ", "id": "Practitioner_qualifications:KDL_doctor"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "KDL_category", "code": "Paramedic_Assistant", "display": "Фельдшер-лаборант", "id": "Practitioner_qualifications:Paramedic_Assistant"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "KDL_category", "code": "Biologist", "display": "Биолог", "id": "Practitioner_qualifications:Biologist"}'::jsonb);
select resource_create('{"resourceType": "Concept", "system": "ValueSet/Practitioner_qualifications", "parentCode": "KDL_category", "code": "Laboratory_assistant", "display": "Лаборант", "id": "Practitioner_qualifications:Laboratory_assistant"}'::jsonb);
