delete from CodeMap r where r.resource ->> 'sourceUrl' = 'ValueSet/ICD-10' and r.resource ->> 'targetUrl' = 'ValueSet/Observation_types';

--todo это временно, пока не дали данные
--Сопоставление диагноз - услуги для маршрутного листа
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A00-A09", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A00-A09", "targetCode": [{"code": "B03.016.004ГМУ_СП", "condition": []}, {"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}, {"code": "A06.30.004", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A15-A19", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A15-A19", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}, {"code": "A06.03.023", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A20-A28", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A20-A28", "targetCode": [{"code": "A04.16.001", "condition": []}, {"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A30-A49", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A30-A49", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A50-A64", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A50-A64", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A65-A69", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A65-A69", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}, {"code": "A06.30.004", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A70-A74", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A70-A74", "targetCode": [{"code": "A04.16.001", "condition": []}, {"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A75-A79", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A75-A79", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A80-A89", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A80-A89", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:A92-A99", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "A92-A99", "targetCode": [{"code": "A04.16.001", "condition": []}, {"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B00-B09", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B00-B09", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B15-B19", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B15-B19", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B20-B24", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B20-B24", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B25-B34", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B25-B34", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B35-B49", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B35-B49", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B50-B64", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B50-B64", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B65-B83", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B65-B83", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B85-B89", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B85-B89", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B90-B94", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B90-B94", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B95-B98", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B95-B98", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
select resource_create('{"resourceType": "CodeMap", "id": "ICD-10_to_Observation_types:B99-B99", "sourceUrl": "ValueSet/ICD-10", "targetUrl": "ValueSet/Observation_types", "sourceCode": "B99-B99", "targetCode": [{"code": "B03.016.006ГМУ_СП", "condition": []}, {"code": "B03.016.002ГМУ_СП", "condition": []}]}'::jsonb);
