# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###                                                                                Пациент зашел в кабинет
###
POST http://localhost:8080/queue/office/patientEntered
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "mode": "working",
  "status": "current",
  "resourceType": "ListResource",
  "id": "12121",
  "entry": [
    {
      "item": {
        "reference": "Location/Office:119",
        "type": "Location"
      }
    },
    {
      "item": {
        "reference": "Patient/b1ed1ac7-ff57-4b5d-95a3-230f560b5fe3",
        "type": "Patient"
      }
    }
  ]
}
###                                                                                Пригласить любого пациента в кабинет
###
POST http://localhost:8080/queue/office/forceSendPatientToObservation
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "mode": "working",
  "status": "current",
  "resourceType": "ListResource",
  "id": "12121",
  "entry": [
    {
      "item": {
        "reference": "Location/Office:119",
        "type": "Location"
      }
    },
    {
      "item": {
        "reference": "Patient/b1ed1ac7-ff57-4b5d-95a3-230f560b5fe3",
        "type": "Patient"
      }
    }
  ]
}
###                                                                                Поставить пациента первым в очередь в кабинет
###
POST http://localhost:8080/queue/office/setAsFirst
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "mode": "working",
  "status": "current",
  "resourceType": "ListResource",
  "id": "12121",
  "entry": [
    {
      "item": {
        "reference": "Location/Office:150",
        "type": "Location"
      }
    },
    {
      "item": {
        "reference": "Patient/1f647c0c-6783-4285-9cca-ac434a4375af",
        "type": "Patient"
      }
    }
  ]
}
###                                                                                Обследования в кабинете завершено
###
POST http://localhost:8080/queue/office/patientLeft
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Location/Office:101",
  "type": "Location"
}
###                                                                                Отменить "вход" пациента в кабинет
###
POST http://localhost:8080/queue/office/cancelEntering
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Location/Office:101",
  "type": "Location"
}
###                                                                                Кабинет готов принять пациента
POST http://localhost:8080/queue/office/ready
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Location/Office:101",
  "type": "Location"
}
###
POST http://localhost:8080/queue/office/ready
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Location/Office:202",
  "type": "Location"
}
###
###                                                                                Кабинет busy
###
POST http://localhost:8080/queue/office/busy
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Location/Office:101",
  "type": "Location"
}
###                                                                                Кабинет closed
###
POST http://localhost:8080/queue/office/closed
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Location/Office:101",
  "type": "Location"
}
###                                                                                Отложить прием ожидаемого пациента в кабинет
###
POST http://localhost:8080/queue/office/delayGoingToObservation
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Patient/e0393e1a-1c72-4e92-90f8-e02f39bab21c",
  "type": "Patient"
}
###
###                                                                                Убрать пациента из очереди
###
DELETE http://localhost:8080/queue/patient
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Patient/e0393e1a-1c72-4e92-90f8-e02f39bab21c",
  "type": "Patient"
}
###
###
DELETE http://localhost:8080/queue
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}
###                                                                                Поставить пациента в очередь
###
POST http://localhost:8080/queue/patient/addToQueue
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Patient/f1613d5c-353c-4825-971f-93db5b4f96e4",
  "type": "Patient"
}
###                                                                              Информация об очереди в кабинет
###
GET http://localhost:8080/queue
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "reference": "Location/Office:104",
  "type": "Location"
}
###                                                                              Информация для монитора для отображения очереди/приема в кабинет/зоне
###
GET http://localhost:8080/queue/locationMonitor?officeId=Office:202
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}
###                                                                              Информация об очереди в целом
###
GET http://localhost:8080/queue/info
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}
###                                                                              Информация об очереди в формате QueueItems
###
GET http://localhost:8080/queue/queueItems
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}
###
GET http://84.201.154.121:8080/queue/info
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}

###                                                                                Непройденные обследования в очереди
###
GET http://localhost:8080/queue/surveys?surveyTypeId=3
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}
###
####                                                                                Удалить очередь
####
DELETE http://localhost:8080/queue
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}
###
###                                                                                Удалить историю
###
DELETE http://localhost:8080/queue/history
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{}
###
###
GET http://localhost:8080/mis-integration/hello
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=
Content-Type: application/json

{}
###