# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/mis-integration/hello
Accept: application/json

###

###

POST http://localhost:8080/reception/severity
Content-Type: application/json

{
  "resourceType": "Bundle",
  "type": "batch",
  "entry": [
    {
      "resource": {
        "id": "3a82aa9f-b7fa-43cf-b00b-d9876d5ae74e",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Heart_rate",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 110
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Blood_pressure_upper_level",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 95
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Degree_of_saturation_of_blood_with_oxygen",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 90
      }
    },
    {
      "resource": {
        "id": "d80684b9-d4e2-4b10-b40a-020b8938367d",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Breathing_rate",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 27
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Body_temperature",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueQuantity": {
          "value": 36.5
        }
      }
    },
    { "resource": {
      "id": "ignored",
      "resourceType": "QuestionnaireResponse",
      "status": "completed",
      "author": {
        "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
        "type": "Practitioner"
      },
      "source": {
        "reference": "Patient/ignored",
        "type": "Patient"
      },
      "questionnaire": "Questionnaire/Severity_criteria",
      "item": [
        {
          "linkId": "Upper_respiratory_airway",
          "text": "Результат осмотра верхних дыхательных путей",
          "answer": [
            {
              "valueCoding": {
                "code": "Airways_passable",
                "display": "Дыхательные пути проходимы",
                "system": "ValueSet/Upper_respiratory_airway"
              }
            }
          ]
        },
        {
          "linkId": "Consciousness_assessment",
          "text": "Сознание",
          "answer": [
            {
              "valueCoding": {
                "code": "Clear_mind",
                "display": "Ясное сознание",
                "system": "ValueSet/Consciousness_assessment"
              }
            }
          ]
        },
        {
          "linkId": "Pain_intensity_assessment",
          "text": "Оценка интенсивности боли (0-10)",
          "answer": [
            {
              "valueCoding": {
                "code": "From_0_to_3",
                "display": "0-3",
                "system": "ValueSet/Pain_intensity_assessment"
              }
            }
          ]
        },
        {
          "linkId": "Patient_can_stand",
          "text": "Опорная функция",
          "answer": [
            {
              "valueCoding": {
                "code": "Can_stand",
                "display": "Может стоять",
                "system": "ValueSet/Patient_can_stand"
              }
            }
          ]
        },
        {
          "linkId": "Questionnaire/paramedic-qa-form/complaints",
          "text": "Жалобы пациента",
          "answer": [
            {
              "valueString": "Озноб"
            },
            {
              "valueString": "Слабость"
            },
            {
              "valueString": "Недомогание"
            }
          ]
        },
        {
          "linkId": "Questionnaire/paramedic-qa-form/base-syndrom",
          "text": "Ведущий синдром",
          "answer": [
            {
              "valueString": "Высокая температура"
            }
          ]
        }
      ]
    }
    }
  ],
  "id": "ignored"
}

###

POST http://localhost:8080/reception/serviceRequests
Content-Type: application/json

{"mode": "working", "status": "current", "resourceType": "ListResource", "id":"12121","entry": [{"item" : {"reference": "Concept/ICD-10/", "type": "Concept"}}]}

###

POST http://localhost:8080/reception/diagnostic
Content-Type: application/json

{
  "resourceType": "Bundle",
  "type": "batch",
  "entry": [
    {
      "resource": {
        "id": "3a82aa9f-b7fa-43cf-b00b-d9876d5ae74e",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Heart_rate",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 110
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Blood_pressure_upper_level",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 95
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Degree_of_saturation_of_blood_with_oxygen",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 90
      }
    },
    {
      "resource": {
        "id": "d80684b9-d4e2-4b10-b40a-020b8938367d",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Breathing_rate",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 27
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Body_temperature",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueQuantity": {
          "value": 36.5
        }
      }
    },
    { "resource": {
      "id": "ignored",
      "resourceType": "QuestionnaireResponse",
      "status": "completed",
      "author": {
        "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
        "type": "Practitioner"
      },
      "source": {
        "reference": "Patient/ignored",
        "type": "Patient"
      },
      "questionnaire": "Questionnaire/Severity_criteria",
      "item": [
        {
          "linkId": "Upper_respiratory_airway",
          "text": "Результат осмотра верхних дыхательных путей",
          "answer": [
            {
              "valueCoding": {
                "code": "Airways_passable",
                "display": "Дыхательные пути проходимы",
                "system": "ValueSet/Upper_respiratory_airway"
              }
            }
          ]
        },
        {
          "linkId": "Consciousness_assessment",
          "text": "Сознание",
          "answer": [
            {
              "valueCoding": {
                "code": "Clear_mind",
                "display": "Ясное сознание",
                "system": "ValueSet/Consciousness_assessment"
              }
            }
          ]
        },
        {
          "linkId": "Pain_intensity_assessment",
          "text": "Оценка интенсивности боли (0-10)",
          "answer": [
            {
              "valueCoding": {
                "code": "From_0_to_3",
                "display": "0-3",
                "system": "ValueSet/Pain_intensity_assessment"
              }
            }
          ]
        },
        {
          "linkId": "Patient_can_stand",
          "text": "Опорная функция",
          "answer": [
            {
              "valueCoding": {
                "code": "Can_stand",
                "display": "Может стоять",
                "system": "ValueSet/Patient_can_stand"
              }
            }
          ]
        },
        {
          "linkId": "Questionnaire/paramedic-qa-form/complaints",
          "text": "Жалобы пациента",
          "answer": [
            {
              "valueString": "Озноб"
            },
            {
              "valueString": "Слабость"
            },
            {
              "valueString": "Недомогание"
            }
          ]
        },
        {
          "linkId": "Questionnaire/paramedic-qa-form/base-syndrom",
          "text": "Ведущий синдром",
          "answer": [
            {
              "valueString": "Высокая температура"
            }
          ]
        }
      ]
    }
    }
  ],
  "id": "ignored"
}

###

POST http://localhost:8080/reception/patient
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0R0doZEpwbGRjenhjbmFzdzg3NDU=

{
  "resourceType": "Bundle",
  "type": "batch",
  "entry": [
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Claim",
        "identifier": [
          {
            "value": "12382(Номер обращения)",
            "type": {
              "coding": [
                {
                  "code": "CLAIM_NUMBER",
                  "system": "ValueSet/Identifier_types"
                }
              ]
            },
            "use": "official"
          }],
        "status": "active",
        "accident": {
          "date": "2019-01-01T00:57:04.242+0000",
          "type": {
            "coding": [
              {
                "code": "travma(еще нет кодов)",
                "system": "ValueSet/Claim_accident_types"
              }
            ]
          }
        },
        "patient": {
          "reference": "Patient/ignored",
          "type": "Patient"
        }
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Heart_rate",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 110
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "ServiceRequest",
        "status": "active",
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "code": {
          "coding": [
            {
              "code": "Surgeon",
              "system": "ValueSet/Observation_types"
            }
          ]
        }
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "ServiceRequest",
        "status": "active",
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "code": {
          "coding": [
            {
              "code": "OAK",
              "system": "ValueSet/Observation_types"
            }
          ]
        }
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "ServiceRequest",
        "status": "active",
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "code": {
          "coding": [
            {
              "code": "X_ray_of_the_leg",
              "system": "ValueSet/Observation_types"
            }
          ]
        }
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "ServiceRequest",
        "status": "active",
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "code": {
          "coding": [
            {
              "code": "Urologist",
              "system": "ValueSet/Observation_types"
            }
          ]
        }
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Blood_pressure_upper_level",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 95
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Degree_of_saturation_of_blood_with_oxygen",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 90
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Breathing_rate",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueInteger": 27
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "Observation",
        "status": "registered",
        "issued": "1970-01-01T00:57:04.242+0000",
        "code": {
          "coding": [
            {
              "code": "Body_temperature",
              "system": "ValueSet/Observation_types"
            }
          ]
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "valueQuantity": {
          "value": 36.5
        }
      }
    },
    {
      "resource": {
        "id": "ignored",
        "resourceType": "DiagnosticReport",
        "subject": {
          "reference": "Patient/ignored",
          "type": "Patient"
        },
        "performer": [
          {
            "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
            "type": "Practitioner"
          }
        ],
        "conclusionCode": [
          {
            "coding": [
              {
                "code": "A00.0",
                "system": "ValueSet/ICD-10"
              }
            ]
          }
        ],
        "status": "preliminary"
      }
    },
    {
      "resource": {
        "id": "ignored",
        "identifier": [
          {
            "value": "7878 77521487",
            "period": {
              "start": "1970-01-01T00:20:22.222+0000"
            },
            "type": {
              "coding": [
                {
                  "code": "PASSPORT",
                  "system": "ValueSet/Identifier_types"
                }
              ]
            },
            "use": "official",
            "assigner": {
              "display": "ОУФМС по ТО..."
            }
          },
          {
            "value": "7878 77521487",
            "period": {
              "start": "1970-01-01T00:20:22.222+0000",
              "end": "1970-01-01T00:20:22.222+0000"
            },
            "type": {
              "coding": [
                {
                  "code": "DIGITAL_ASSURANCE",
                  "system": "ValueSet/Identifier_types"
                }
              ]
            },
            "use": "official",
            "assigner": {
              "display": "ОУФМС по ТО..."
            }
          },
          {
            "value": "7878 11111",
            "type": {
              "coding": [
                {
                  "code": "ENP",
                  "system": "ValueSet/Identifier_types"
                }
              ]
            },
            "use": "official"
          },
          {
            "value": "7878 77521487",
            "type": {
              "coding": [
                {
                  "code": "SNILS",
                  "system": "ValueSet/Identifier_types"
                }
              ]
            },
            "use": "official"
          },
          {
            "value": "7878 77521487",
            "type": {
              "coding": [
                {
                  "code": "BRACELET",
                  "system": "ValueSet/Identifier_types"
                }
              ]
            },
            "use": "official"
          }
        ],
        "resourceType": "Patient",
        "name": [
          {
            "use": "official",
            "text": "Петров И. А.",
            "family": "Петров",
            "given": [
              "Иван",
              "Алекссандрович"
            ]
          }
        ],
        "birthDate": "2019-10-11T04:07:05.243+0000",
        "gender": "female",
        "extension": {
          "nationality": "Russian",
          "birthPlace": {
            "use": "home",
            "type": "both",
            "text": "Россия ТО г. Томск",
            "city": "Tomsk",
            "state": "TO",
            "country": "Russia"
          }
        },
        "age": 0
      }
    },
    { "resource": {
      "id": "ignored",
      "resourceType": "QuestionnaireResponse",
      "status": "completed",
      "author": {
        "reference": "Practitioner/37030497-7d8b-48ec-a5cf-5f3097c813ac",
        "type": "Practitioner"
      },
      "source": {
        "reference": "Patient/ignored",
        "type": "Patient"
      },
      "questionnaire": "Questionnaire/Severity_criteria",
      "item": [
        {
          "linkId": "Upper_respiratory_airway",
          "text": "Результат осмотра верхних дыхательных путей",
          "answer": [
            {
              "valueCoding": {
                "code": "Airways_passable",
                "display": "Дыхательные пути проходимы",
                "system": "ValueSet/Upper_respiratory_airway"
              }
            }
          ]
        },
        {
          "linkId": "Consciousness_assessment",
          "text": "Сознание",
          "answer": [
            {
              "valueCoding": {
                "code": "Clear_mind",
                "display": "Ясное сознание",
                "system": "ValueSet/Consciousness_assessment"
              }
            }
          ]
        },
        {
          "linkId": "Pain_intensity_assessment",
          "text": "Оценка интенсивности боли (0-10)",
          "answer": [
            {
              "valueCoding": {
                "code": "From_0_to_3",
                "display": "0-3",
                "system": "ValueSet/Pain_intensity_assessment"
              }
            }
          ]
        },
        {
          "linkId": "Patient_can_stand",
          "text": "Опорная функция",
          "answer": [
            {
              "valueCoding": {
                "code": "Can_stand",
                "display": "Может стоять",
                "system": "ValueSet/Patient_can_stand"
              }
            }
          ]
        },
        {
          "linkId": "Severity",
          "text": "Результат сортировки",
          "answer": [
            {
              "valueCoding": {
                "code": "RED",
                "display": "Красный",
                "system": "ValueSet/Sorting_result"
              }
            }
          ]
        },
        {
          "linkId": "Questionnaire/paramedic-qa-form/complaints",
          "text": "Жалобы пациента",
          "answer": [
            {
              "valueString": "Озноб"
            },
            {
              "valueString": "Слабость"
            },
            {
              "valueString": "Недомогание"
            }
          ]
        },
        {
          "linkId": "Questionnaire/paramedic-qa-form/base-syndrom",
          "text": "Ведущий синдром",
          "answer": [
            {
              "valueString": "Высокая температура"
            }
          ]
        }
      ]
    }},
    { "resource":  {
      "id": "2fa4a612-dffe-4382-a03b-804fc48263e7",
      "resourceType": "ServiceRequest",
      "status": "active",
      "subject": {
        "reference": "Patient/1a77ce5f-8473-4627-84b0-b1ddc5c46364",
        "type": "Patient"
      },
      "code": {
        "coding": [
          {
            "code": "Surgeon",
            "display": "Осмотр хирурга",
            "system": "ValueSet/Observation_types"
          }
        ]
      }
    }}
  ],
  "id": "ignored"
}

###